name: Test on Ubuntu

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install app dependencies
      run: npm i
    - name: Get TestCafe version
      uses: DevExpress/testcafe-action@latest
      with:
        args: "-v"
    - name: Run TestCafe Tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome:headless test.js"
